import {CLI_POLICY} from '../src/cli-policy.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {ensureHourlyModeSchema,normalizeModeTarget,modeTargetKey} from '../src/fleet-hourly-modes.js';
import {activateAutomationTargets,stopAutomationGate,automationAllowed,automationFenceSql,automationCommitStatement} from '../src/fleet-automation-control.js';
const source=readFileSync(new URL('../src/index.js',import.meta.url),'utf8');
function fn(name){const start=source.indexOf('async function '+name+'(');return source.slice(start,source.indexOf('\n}',start)+2);}
async function setup(){const raw=new DatabaseSync(':memory:');function statement(sql,args=[]){return {sql,args,bind(...values){return statement(sql,values);},async run(){return {meta:{changes:Number(raw.prepare(sql).run(...args).changes)}};},async all(){return {results:raw.prepare(sql).all(...args)};},async first(){return raw.prepare(sql).get(...args)||null;}};}
const DB={raw,exec:async sql=>raw.exec(sql),prepare:statement,async batch(rows){raw.exec('BEGIN');try{const results=rows.map(row=>({meta:{changes:Number(raw.prepare(row.sql).run(...row.args).changes)}}));raw.exec('COMMIT');return results;}catch(error){raw.exec('ROLLBACK');throw error;}}};const env={DB};await ensureHourlyModeSchema(env);raw.exec('CREATE TABLE decisions(id TEXT PRIMARY KEY,machine,agent,surface,question,options,recommended,status,created_at,deadline,url,mission,project,project_slug,parent_decision,batch_id,option_targets);CREATE TABLE test_missions(id TEXT PRIMARY KEY);');return env;}
function prepared(persona='Morfeo'){const target=normalizeModeTarget({persona,machine:'MacMini',runtime:'Claude',host:'app'});return {target,key:modeTargetKey(target),project:{id:'yokup'}};}
const now=1788595200000;

test('Stop global seguido de activar sólo A conserva B pausado incluso para horas futuras',async()=>{const env=await setup(),a=prepared(),b=prepared('Neo');await activateAutomationTargets(env,'learning',[a,b],[],0,'owner',now);const previous=env.DB.raw.prepare('SELECT * FROM fleet_agent_modes').all();await stopAutomationGate(env,'learning','',now+100);await activateAutomationTargets(env,'learning',[a],previous,2,'owner',now+200,false);assert.equal((await automationAllowed(env,'learning',a.key,now+3600000)).allowed,true);assert.equal((await automationAllowed(env,'learning',b.key,now+3600000)).allowed,false);});

test('la ventana y su vínculo exacto se insertan juntos; Stop intercalado impide una publicación tardía',async()=>{const env=await setup(),a=prepared();const context={CLI_POLICY,ensureHourlyModeSchema,automationFenceSql};vm.runInNewContext(fn('guardedAutomaticDecisionInsert')+';this.insert=guardedAutomaticDecisionInsert',context);const values=['DEC1','MacMini','MorfeoMacMini','highscore','Pregunta','[]',0,now,now+300000,'','Training horario','yokup','YOKUP','','','[]'];await context.insert(env,values,'training',a.key,now);assert.equal(env.DB.raw.prepare('SELECT identity_key FROM fleet_automation_decisions').get().identity_key,a.key);await stopAutomationGate(env,'training',a.key,now+1);await assert.rejects(context.insert(env,['DEC2',...values.slice(1)],'training',a.key,now),/automation_stopped/);assert.equal(env.DB.raw.prepare('SELECT COUNT(*) n FROM decisions').get().n,1);assert.equal(env.DB.raw.prepare('SELECT COUNT(*) n FROM fleet_automation_decisions').get().n,1);});

test('fence de materialización revierte toda la transacción tras Stop individual, sin tocar misión humana',async()=>{const env=await setup(),a=prepared();await stopAutomationGate(env,'training',a.key,now+1);await assert.rejects(env.DB.batch([automationCommitStatement(env,{mode:'training',key:a.key,created_at:now}),env.DB.prepare("INSERT INTO test_missions VALUES('automatic')")]),/automation_stopped/);assert.equal(env.DB.raw.prepare('SELECT COUNT(*) n FROM test_missions').get().n,0);await env.DB.prepare("INSERT INTO test_missions VALUES('human')").run();assert.equal(env.DB.raw.prepare('SELECT id FROM test_missions').get().id,'human');});

test('CAS de entrega no puede comunicar completed después de Stop aunque un guard anterior pasó',async()=>{const env=await setup(),a=prepared();env.DB.raw.prepare("INSERT INTO fleet_agent_mode_runs(id,identity_key,hour_start,mode,project_id,status,created_at,updated_at) VALUES(?,?,?,'learning','yokup','awaiting_delivery',?,?)").run('run',a.key,now,now,now);await stopAutomationGate(env,'learning','',now+1);const result=await env.DB.prepare("UPDATE fleet_agent_mode_runs SET status='completed' WHERE id='run'").run();assert.equal(result.meta.changes,0);assert.equal(env.DB.raw.prepare('SELECT status FROM fleet_agent_mode_runs').get().status,'awaiting_delivery');});

test('GET/POST módulos sólo se evalúa después de requireAuth; no autoriza executor para configuración',()=>{const start=source.indexOf("if(url.pathname==='/fleet/automation-modules')"),end=source.indexOf('if (["/fleet/agent/mode"',start),route=source.slice(start,end);assert.ok(route.indexOf('requireAuth')<route.indexOf('changeAutomationModule'));assert.match(route,/if\(!session\)return json\(\{ok:false,error:'unauthorized'\},401\)/);assert.doesNotMatch(route,/authorizeCliExecutor/);});
