-- Additive calls workspace. Test cases never create real IoT incidents or notifications.
CREATE TABLE call_operators(email TEXT NOT NULL,retailer_id TEXT NOT NULL REFERENCES retailer_accounts(id),granted_by TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(email,retailer_id));
CREATE TABLE call_cases(id TEXT PRIMARY KEY,incident_id TEXT UNIQUE REFERENCES installer_incidents(id),retailer_id TEXT REFERENCES retailer_accounts(id),title TEXT NOT NULL,site_name TEXT NOT NULL,latitude REAL NOT NULL,longitude REAL NOT NULL,skill TEXT NOT NULL,circuit_id TEXT,priority TEXT NOT NULL DEFAULT 'normal',is_test INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,stage TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL);
CREATE TABLE call_contacts(case_id TEXT NOT NULL REFERENCES call_cases(id),kind TEXT NOT NULL CHECK(kind IN ('retailer','installer')),name TEXT NOT NULL,phone TEXT,language TEXT NOT NULL DEFAULT 'es-ES',timezone TEXT NOT NULL DEFAULT 'Europe/Madrid',PRIMARY KEY(case_id,kind));
CREATE TABLE call_jobs(id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES call_cases(id),target TEXT NOT NULL CHECK(target IN ('retailer','installer')),purpose TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',mode TEXT NOT NULL DEFAULT 'human',owner TEXT,lease_until INTEGER,attempt_id TEXT,retry_at INTEGER,created_at INTEGER NOT NULL,UNIQUE(case_id,target));
CREATE TABLE call_attempts(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES call_jobs(id),actor TEXT NOT NULL,mode TEXT NOT NULL,channel TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'started',outcome TEXT,notes TEXT,availability TEXT,created_at INTEGER NOT NULL,ended_at INTEGER);
CREATE UNIQUE INDEX call_one_live_attempt ON call_attempts(job_id) WHERE ended_at IS NULL;
CREATE TABLE call_events(id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES call_cases(id),actor TEXT NOT NULL,kind TEXT NOT NULL,detail TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE call_proposals(id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES call_cases(id),version INTEGER NOT NULL,installer_id TEXT NOT NULL,start_at INTEGER NOT NULL,end_at INTEGER NOT NULL,timezone TEXT NOT NULL,scope TEXT NOT NULL,cost_cents INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'EUR',status TEXT NOT NULL DEFAULT 'proposed',retailer_accepted INTEGER NOT NULL DEFAULT 0,installer_accepted INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(case_id,version));
CREATE UNIQUE INDEX call_current_proposal ON call_proposals(case_id) WHERE status IN ('proposed','confirmed');
CREATE TABLE call_acceptances(proposal_id TEXT NOT NULL REFERENCES call_proposals(id),party TEXT NOT NULL,actor TEXT NOT NULL,evidence TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(proposal_id,party));
CREATE TABLE call_rooms(id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL UNIQUE REFERENCES call_attempts(id),host_hash TEXT NOT NULL,guest_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,closed_at INTEGER,offer TEXT,answer TEXT);
CREATE TABLE call_signals(room_id TEXT NOT NULL REFERENCES call_rooms(id),sender TEXT NOT NULL,seq INTEGER NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(room_id,sender,seq));
CREATE INDEX call_jobs_queue ON call_jobs(status,retry_at,created_at);
CREATE INDEX call_events_case ON call_events(case_id,created_at);
CREATE TABLE call_tokens(id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,email TEXT NOT NULL,label TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL,revoked_at INTEGER);
