import {SCRIPT,pilotReply,speak} from './call-pilot.mjs';
import {mountRoom} from './call-room.mjs';
const $=s=>document.querySelector(s),base=['localhost','127.0.0.1'].includes(location.hostname)?location.origin+'/api/calls':'https://data.yokup.com/api/calls';
const E=(tag,value,cls)=>{const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n;};
const names={pending:'Pendiente',reserved:'Reservada',in_call:'En conversación',retry:'Para reintentar',done:'Finalizada',open:'Abierta',assigned:'Asignada',scheduled:'Cita confirmada',repairing:'En reparación',awaiting_rating:'Por valorar',closed:'Cierre satisfactorio',reopened:'Reabierta',proposed:'Pendiente de aceptación',confirmed:'Confirmada',superseded:'Sustituida',cancelled:'Cancelada',retailer:'Comercio',installer:'Técnico',human:'Persona',assistant:'Asistente de prueba',availability:'Disponibilidad recogida',agreed:'Acuerdo verbal',declined:'Rechazo',no_answer:'Sin respuesta',busy:'Ocupado',voicemail:'Buzón',human_handoff:'Derivación a una persona',other:'Otro resultado'};
const eventNames={pilot_created:'Expediente de prueba creado',reserved:'Llamada reservada',attempt_started:'Intento iniciado',call_result:'Resultado registrado',proposal_created:'Propuesta creada',proposal_acceptance:'Aceptación registrada',proposal_cancelled:'Propuesta cancelada',pilot_stage:'Seguimiento del piloto',contact_updated:'Contacto actualizado'};
const detailNames={version:'Versión',party:'Participante',evidence:'Confirmación',notes:'Notas',availability:'Disponibilidad',outcome:'Resultado',mode:'Modalidad',meaning:'Estado de conexión',to:'Nuevo estado',kind:'Contacto'};
let me,all=[],selected=null,current,map,jobId,busy=false,recognition;
const status=t=>$('#status').textContent=t;
async function api(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok){if(r.status===401){$('#workspace').hidden=true;$('#login').hidden=false;$('#case').replaceChildren();selected=null;}throw Error(d.error||'No se pudo completar la operación.');}return d;}
async function act(fn){if(busy)return;busy=true;try{status('Guardando…');await fn();status('Guardado.');}catch(e){status(e.message);}finally{busy=false;}}
function button(label,fn,cls='text-button'){const b=E('button',label,cls);b.type='button';b.onclick=()=>act(fn);return b;}
function queue(){const search=$('#search').value.toLowerCase(),state=$('#filter').value,type=$('#test-filter').value;const host=$('#queue');host.replaceChildren();const items=all.filter(c=>(!state||c.call_status===state)&&(!type||(type==='test')===!!c.is_test)&&(!search||[c.title,c.site_name,c.circuit_id].join(' ').toLowerCase().includes(search)));
 for(const c of items){const b=button('',()=>loadCase(c.id,c.job_id),'queue-card');b.setAttribute('aria-pressed',String(selected===c.id&&jobId===c.job_id));b.append(E('strong',c.title),E('small',c.site_name+' · '+names[c.target]),E('small',names[c.call_status]+(c.call_owner?' · '+c.call_owner:'')));if(c.is_test)b.append(E('span','PRUEBA','pill'));host.append(b);}if(!items.length)host.append(E('p','No hay llamadas para estos filtros.','muted'));
}
async function refresh(){const d=await api('/cases');all=d.cases;queue();}
function line(container,label,value){container.append(E('p',label+': '+value));}
async function loadCase(id,jid){const d=await api('/cases/'+encodeURIComponent(id));current=d;selected=id;jobId=jid||d.jobs[0]?.id;renderCase();queue();}
function section(title){const n=E('section',undefined,'case-section');n.append(E('h3',title));$('#case').append(n);return n;}
function renderCase(){
 recognition?.stop();map?.remove();map=null;$('#empty').hidden=true;const host=$('#case');host.hidden=false;host.replaceChildren();const d=current,c=d.case,j=d.jobs.find(x=>x.id===jobId)||d.jobs[0];jobId=j.id;
 const header=E('div',undefined,'case-header');header.append(E('h2',c.title),E('span',c.is_test?'EXPEDIENTE DE PRUEBA':names[c.stage]||c.stage,'pill'));host.append(header,E('p',c.site_name+(c.circuit_id?' · '+c.circuit_id:''),'muted'));
 const mapEl=E('div',undefined,'case-map');mapEl.setAttribute('aria-label','Ubicación de la incidencia y técnicos candidatos');host.append(mapEl);
 if(window.maplibregl){try{map=new maplibregl.Map({container:mapEl,style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',center:[c.longitude,c.latitude],zoom:1.6,scrollZoom:false,attributionControl:{compact:true}});map.on('load',()=>{if(!map)return;new maplibregl.Marker({color:'#a55036'}).setLngLat([c.longitude,c.latitude]).addTo(map);for(const t of d.candidates)new maplibregl.Marker({color:'#67935c'}).setLngLat([t.longitude,t.latitude]).addTo(map);const points=[[c.longitude,c.latitude],...d.candidates.map(t=>[t.longitude,t.latitude])],bounds=points.reduce((b,p)=>b.extend(p),new maplibregl.LngLatBounds(points[0],points[0]));map.fitBounds(bounds,{padding:45,maxZoom:12,duration:window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:1000});});}catch{mapEl.textContent='Ubicación: '+c.latitude+', '+c.longitude;}}else mapEl.textContent='Ubicación: '+c.latitude+', '+c.longitude;
 const call=section('Contacto · '+names[j.target]);line(call,'Objetivo',j.purpose);line(call,'Estado',names[j.status]||j.status);if(j.owner)line(call,'Responsable',j.owner);
 const contacts=d.contacts.find(x=>x.kind===j.target)||{};const details=E('details');details.append(E('summary','Datos del contacto'));const form=E('form',undefined,'form-grid');form.innerHTML='<label>Nombre<input name="name" required maxlength="120"></label><label>Teléfono autorizado<input name="phone" type="tel" placeholder="+34…"></label><label>Idioma<select name="language"><option value="es-ES">Español</option><option value="pt-PT">Portugués</option><option value="en-GB">Inglés</option></select></label><label>Zona horaria<input name="timezone" required value="Europe/Madrid"></label><button class="primary">Guardar contacto</button>';
 for(const key of ['name','phone','language','timezone'])if(contacts[key])form.elements[key].value=contacts[key];form.onsubmit=e=>{e.preventDefault();act(async()=>{await api('/cases/'+encodeURIComponent(c.id)+'/contacts',{...Object.fromEntries(new FormData(form)),kind:j.target});await loadCase(c.id,j.id);});};details.append(form);call.append(details);
 const actions=E('div',undefined,'case-actions');
 if(j.status==='pending'||j.status==='reserved'&&(j.owner===me.email||j.lease_until<Date.now())){
 actions.append(button('Reservar para una persona',async()=>{await api('/jobs/'+encodeURIComponent(j.id)+'/claim',{mode:'human'});await loadCase(c.id,j.id);await refresh();},'primary'));
 if(c.is_test)actions.append(button('Reservar para asistente de prueba',async()=>{await api('/jobs/'+encodeURIComponent(j.id)+'/claim',{mode:'assistant'});await loadCase(c.id,j.id);await refresh();}));
 }
 const ai=button('Telefonía IA · sin activar',()=>{});ai.disabled=true;actions.append(ai);call.append(actions);
 if(j.owner===me.email&&j.status==='reserved'){
 const starts=E('div',undefined,'case-actions');
 const startCall=async channel=>{const request_key=crypto.randomUUID();const at=await api('/jobs/'+encodeURIComponent(j.id)+'/start',{channel,request_key});if(at.tel)location.href=at.tel;await loadCase(c.id,j.id);await refresh();};
 if(j.mode==='human'){starts.append(button('Iniciar llamada web gratuita',()=>startCall('browser'),'primary'));const tel=button('Llamar con mi teléfono',()=>startCall('manual'));tel.disabled=!contacts.phone;starts.append(tel);}else starts.append(button('Iniciar conversación de prueba',()=>startCall('pilot'),'primary'));
 starts.append(button('Liberar reserva',async()=>{await api('/jobs/'+encodeURIComponent(j.id)+'/release',{});await loadCase(c.id,j.id);await refresh();}));call.append(starts);
 }
 if(j.owner===me.email&&j.status==='in_call'){
 const attempt=d.attempts.find(t=>t.id===j.attempt_id);if(attempt?.channel==='browser'){
  const roomActions=E('div',undefined,'case-actions');const storeKey='yokup-call-room:'+attempt.id;let cached;try{cached=JSON.parse(sessionStorage.getItem(storeKey));}catch{}
  const showRoom=data=>{roomActions.replaceChildren();const url=role=>location.origin+'/llamadas?room='+encodeURIComponent(data.id)+'#token='+data[role+'_token'];const hostLink=E('a','Abrir mi sala','primary');hostLink.href=url('host');hostLink.target='_blank';hostLink.rel='noopener';roomActions.append(hostLink,button('Copiar invitación para el contacto',async()=>{await navigator.clipboard.writeText(url('guest'));}));roomActions.append(E('p','La invitación da acceso a esta sala durante una hora. Compártela solo con la persona que participará.','small'));};
  if(cached)showRoom(cached);else roomActions.append(button('Crear sala e invitación',async()=>{const data=await api('/jobs/'+encodeURIComponent(j.id)+'/room',{});sessionStorage.setItem(storeKey,JSON.stringify(data));showRoom(data);},'primary'));call.append(roomActions);
 }
 const result=E('form',undefined,'form-grid');result.innerHTML='<label>Resultado<select name="outcome"><option value="availability">Disponibilidad recogida</option><option value="agreed">Acuerdo verbal recogido</option><option value="declined">Rechazo</option><option value="no_answer">Sin respuesta</option><option value="busy">Ocupado</option><option value="voicemail">Buzón</option><option value="human_handoff">Pasar a una persona</option><option value="other">Otro resultado</option></select></label><label>Reintentar (opcional)<input type="datetime-local" name="retry_at"></label><label class="wide">Disponibilidad y persona de acceso<textarea name="availability" maxlength="1000"></textarea></label><label class="wide">Notas de la conversación<textarea name="notes" required minlength="3" maxlength="2000"></textarea></label><p class="wide accept-note">Registrar una conversación no confirma la cita. Las aceptaciones se registran sobre la propuesta concreta.</p><button class="primary">Guardar resultado y terminar</button>';
 if(attempt?.channel==='pilot')call.append(pilotPanel(result,contacts.language||'es-ES'));
 result.onsubmit=e=>{e.preventDefault();act(async()=>{const b=Object.fromEntries(new FormData(result));b.retry_at=b.retry_at?Date.parse(b.retry_at):null;await api('/jobs/'+encodeURIComponent(j.id)+'/finish',b);window.speechSynthesis?.cancel();await loadCase(c.id,j.id);await refresh();});};call.append(result);
 }
 const proposalSection=section('Propuesta de intervención');proposalSection.append(E('p','Candidatos compatibles a menos de 40 km. La visita requiere la aceptación expresa de comercio y técnico.'));
 const active=d.proposals.find(p=>['proposed','confirmed'].includes(p.status));
 if(active){const p=E('div',undefined,'proposal');p.append(E('strong','Propuesta '+active.version+' · '+names[active.status]));line(p,'Visita',new Date(active.start_at).toLocaleString('es-ES',{timeZone:active.timezone})+' — '+new Date(active.end_at).toLocaleTimeString('es-ES',{timeZone:active.timezone})+' · '+active.timezone);line(p,'Trabajo',active.scope);line(p,'Importe',(active.cost_cents/100).toFixed(2)+' '+active.currency);line(p,'Aceptaciones','Comercio '+(active.retailer_accepted?'✓':'pendiente')+' · Técnico '+(active.installer_accepted?'✓':'pendiente'));
 if(active.status==='proposed'){
 const af=E('form',undefined,'form-grid');af.innerHTML='<label>Quién acepta<select name="party"><option value="retailer">Comercio</option><option value="installer">Técnico</option></select></label><label>Confirmación recibida<input name="evidence" required minlength="10" maxlength="1000" placeholder="Quién, cuándo y qué ha aceptado"></label><label class="inline-check wide"><input name="confirmed" type="checkbox" required>He recibido la aceptación expresa de esta propuesta y su importe.</label><button class="primary">Registrar aceptación</button>';
 af.onsubmit=e=>{e.preventDefault();act(async()=>{const out=await api('/proposals/'+active.id+'/accept',{party:af.elements.party.value,evidence:af.elements.evidence.value,accepted:true,verbal_confirmed:af.elements.confirmed.checked});await loadCase(c.id,j.id);if(out.conflict)throw Error('Ambas respuestas están guardadas, pero hay un conflicto de agenda o asignación. La cita no está confirmada.');});};p.append(af);
 }
 const cancel=E('form',undefined,'form-grid');cancel.innerHTML='<label>Motivo de cancelación<input name="evidence" required minlength="10"></label><button class="text-button">Cancelar propuesta</button>';cancel.onsubmit=e=>{e.preventDefault();act(async()=>{await api('/proposals/'+active.id+'/cancel',{evidence:cancel.elements.evidence.value});await loadCase(c.id,j.id);});};if(!['repairing','awaiting_rating','closed'].includes(c.stage))p.append(cancel);proposalSection.append(p);
 }
 if((!active||active.status==='proposed')&&!['repairing','awaiting_rating','closed'].includes(c.stage)){
 const pf=E('form',undefined,'form-grid');pf.innerHTML='<label class="wide">Instalador<select name="installer_id" required></select></label><label>Inicio (hora de este navegador)<input name="start_at" type="datetime-local" required></label><label>Fin (hora de este navegador)<input name="end_at" type="datetime-local" required></label><label>Zona horaria para la cita<input name="timezone" value="Europe/Madrid" required></label><label>Importe total EUR<input name="euros" type="number" step="0.01" min="0" max="10000" required></label><label class="wide">Trabajo previsto<textarea name="scope" minlength="5" required></textarea></label><button class="primary">Guardar nueva propuesta</button>';
 for(const t of d.candidates){const o=E('option',t.name+' · '+t.distance_km.toFixed(1)+' km');o.value=t.id;pf.elements.installer_id.append(o);}if(!d.candidates.length){pf.querySelector('button').disabled=true;proposalSection.append(E('p','No hay técnicos disponibles con esta especialidad en el radio inicial.','warning'));}
 pf.onsubmit=e=>{e.preventDefault();act(async()=>{const b=Object.fromEntries(new FormData(pf));await api('/cases/'+encodeURIComponent(c.id)+'/proposals',{...b,start_at:new Date(b.start_at).toISOString(),end_at:new Date(b.end_at).toISOString(),cost_cents:Math.round(Number(b.euros)*100),previous_id:active?.id||null});await loadCase(c.id,j.id);await refresh();});};proposalSection.append(pf);
 }
 if(c.is_test){const p=section('Seguimiento del piloto');p.append(E('span',names[c.stage]||c.stage,'pill'));if(['scheduled','repairing','awaiting_rating','reopened'].includes(c.stage)){const f=E('form',undefined,'form-grid');f.innerHTML='<label class="wide">Evidencia de prueba<textarea name="notes" required minlength="5"></textarea></label><label>Resultado<select name="satisfied"><option value="yes">Satisfactorio</option><option value="no">Sigue fallando</option></select></label><button class="primary">Registrar siguiente paso del piloto</button>';f.onsubmit=e=>{e.preventDefault();act(async()=>{await api('/cases/'+encodeURIComponent(c.id)+'/advance',{notes:f.elements.notes.value,satisfied:f.elements.satisfied.value==='yes'});await loadCase(c.id,j.id);await refresh();});};p.append(f);}p.append(E('p','Los pasos de este expediente son pruebas. No modifican equipos ni notifican a profesionales reales.','small muted'));}
 else {const p=section('Estado de la intervención');line(p,'Estado técnico',d.incident?.status||'pendiente');if(d.incident?.resolution)line(p,'Resolución',d.incident.resolution);line(p,'Valoración',d.rating?(d.rating.satisfied?'Satisfactoria':'Revisión solicitada')+' · '+d.rating.stars+'/5':'Pendiente del comercio');}
 const timeline=section('Historial compartido'),ul=E('ul',undefined,'timeline');for(const e of d.events.slice(-50).reverse()){const li=E('li');li.append(E('time',new Date(e.created_at).toLocaleString()),E('strong',(eventNames[e.kind]||'Actividad')+' · '+e.actor));let info;try{info=JSON.parse(e.detail);}catch{info={};}li.append(E('p',Object.entries(info).filter(([k,v])=>detailNames[k]&&v!==null).map(([k,v])=>detailNames[k]+': '+(names[v]||v)).join(' · ')));ul.append(li);}timeline.append(ul);
}
function pilotPanel(form,lang){const panel=E('div',undefined,'speech-panel'),prompt=E('blockquote',SCRIPT[0].say),log=E('div',undefined,'speech-log'),input=E('input'),controls=E('div',undefined,'case-actions');input.placeholder='Escribe la respuesta o usa el micrófono';input.setAttribute('aria-label','Respuesta del participante de prueba');let step=0,done=false,turns=[];panel.append(E('strong','Asistente gratuito · conversación con guion'),prompt,log,input,controls,E('p','La voz depende del navegador. El dictado puede usar su servicio de reconocimiento; también puedes completar toda la prueba escribiendo.','small muted'));
 controls.append(button('Escuchar',async()=>{if(!speak(prompt.textContent,lang))throw Error('La voz no está disponible. Continúa por escrito.');}));
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(Recognition){controls.append(button('Dictar respuesta',async()=>{recognition?.stop();recognition=new Recognition();recognition.lang=lang;recognition.onresult=e=>{input.value=e.results[0][0].transcript;};recognition.onerror=()=>status('No se pudo reconocer la voz. Puedes escribir la respuesta.');recognition.start();}));}
 const send=button('Responder',async()=>{if(done)return;const reply=input.value,answer=pilotReply(step,reply);if(answer.error)throw Error(answer.error);turns.push({question:SCRIPT[step].say,answer:reply});log.append(E('p','Participante: '+reply));input.value='';step=answer.index;prompt.textContent=answer.say;if(answer.done){done=true;send.disabled=true;form.elements.outcome.value=answer.outcome;form.elements.availability.value=answer.outcome==='availability'?reply:'';form.elements.notes.value='PILOTO con guion: '+turns.map(t=>t.question+' '+t.answer).join(' / ');}});controls.append(send);return panel;
}
async function operators(){if(!me.admin)return;$('#operators').hidden=false;const d=await api('/operators'),select=$('#operator-form').elements.retailer_id;select.replaceChildren();for(const r of d.retailers){const o=E('option',r.name);o.value=r.id;select.append(o);}$('#operator-list').replaceChildren();for(const o of d.operators){const p=E('p',o.email+' · '+o.retailer_name);p.append(button('Revocar',async()=>{await api('/operators',{email:o.email,retailer_id:o.retailer_id,action:'revoke'});await operators();}));$('#operator-list').append(p);}}
async function tokens(){const d=await api('/tokens');$('#token-list').replaceChildren();for(const t of d.tokens){const row=E('p',t.label+' · '+(t.revoked_at?'Revocado':'Caduca '+new Date(t.expires_at).toLocaleString()));if(!t.revoked_at)row.append(button('Revocar token',async()=>{await api('/tokens',{revoke:t.id});await tokens();}));$('#token-list').append(row);}}
async function init(){const roomId=new URL(location.href).searchParams.get('room'),token=new URLSearchParams(location.hash.slice(1)).get('token')||(roomId&&sessionStorage.getItem('yokup-room:'+roomId));if(roomId&&token){sessionStorage.setItem('yokup-room:'+roomId,token);history.replaceState(null,'',location.pathname+'?room='+encodeURIComponent(roomId));$('.calls-intro').hidden=true;await mountRoom({roomId,token,base});return;}
 try{me=await api('/me');$('#workspace').hidden=false;$('#login').hidden=true;$('#identity').textContent=(me.admin?'Superusuario':'Operador')+' · '+me.email;await refresh();await operators();await tokens();}catch(e){$('#login').hidden=false;status(e.message);}}
let googleSdk;
$('#calls-google').onclick=()=>act(async()=>{
 const access=async(path,body)=>{const r=await fetch('https://data.yokup.com/api/portal-access'+path,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo verificar la cuenta.');return d;};
 if(!window.google?.accounts?.id){if(!googleSdk)googleSdk=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=resolve;s.onerror=()=>{googleSdk=null;s.remove();reject(Error('No se pudo cargar Google. Vuelve a intentarlo.'));};document.head.append(s);});await googleSdk;}
 const challenge=await access('/google/challenge',{});google.accounts.id.initialize({client_id:challenge.google_client_id,nonce:challenge.nonce,auto_select:false,callback:r=>act(async()=>{await access('/google/login',{credential:r.credential,kind:'retailer',intent:'login'});await init();})});$('#calls-google-widget').replaceChildren();google.accounts.id.renderButton($('#calls-google-widget'),{type:'standard',theme:'outline',size:'large',text:'continue_with'});
});
$('#new-pilot').onclick=()=>act(async()=>{const p=await api('/pilot',{});await refresh();await loadCase(p.id);});$('#refresh').onclick=()=>act(async()=>{await refresh();if(selected)await loadCase(selected,jobId);});for(const selector of ['#search','#filter','#test-filter'])$(selector).addEventListener('input',queue);
$('#operator-form').onsubmit=e=>{e.preventDefault();act(async()=>{await api('/operators',{...Object.fromEntries(new FormData(e.target)),action:'grant'});await operators();});};
$('#token-form').onsubmit=e=>{e.preventDefault();act(async()=>{const d=await api('/tokens',{label:e.target.elements.label.value});$('#issued-token').textContent=d.token;$('#issued-token').hidden=false;await tokens();});};
window.addEventListener('pagehide',()=>{recognition?.stop();window.speechSynthesis?.cancel();map?.remove();});
init();
