import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./dashboard.html',import.meta.url),'utf8');
function fn(name){const start=source.search(new RegExp('(?:async )?function '+name+'\\('));assert.ok(start>=0);const tail=source.slice(start),ends=[tail.indexOf('\nfunction '),tail.indexOf('\nasync function '),tail.indexOf('\ndocument.')].filter(n=>n>=0);return tail.slice(0,Math.min(...ends));}
function setup(){const context={Map,Set,URL,encodeURIComponent,decodeURIComponent,Date,console,window:{},esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),AUTOMATION_SELECTIONS:{training:new Map(),learning:new Map()},AUTOMATION_RESULTS:new Map(),AUTOMATION_STATE:null,AUTOMATION_BUSY:false,AUTOMATION_ERROR:'',AUTOMATION_NOTICE:'',AUTOMATION_REVISION:0,AUTOMATION_FETCHED:1,pulseModeSupport:row=>row.support_reason?'Ejecutor no disponible.':'',pulseModeSummary:row=>row.automation_enabled===false?'Producción bloqueada':'Programado',automationRender(){},pulseLoadModes(){},automationLoad(){}};vm.createContext(context);vm.runInContext(readFileSync(new URL('./yk-agent-identity.js',import.meta.url),'utf8'),context);context.ykAgentIdentity=context.window.ykAgentIdentity;for(const name of ['automationUiFamily','automationUiReason','automationUiFamilies','automationModuleHtml','automationAccept','automationHandle'])vm.runInContext(fn(name),context);return context;}
const app={agent:'MorfeoMacMini',persona:'Morfeo',machine:'MacMini',runtime:'Claude',host:'app',identity_key:'morfeo|mini|claude|app',mode:'manual',available_modes:['manual','learning','training']},cli={...app,host:'cli',identity_key:'morfeo|mini|claude|cli',available_modes:['manual'],support_reason:'consumer_unavailable'};
function state(items=[app,cli]){return {items,categories:[{mode:'training',enabled:true,revision:0},{mode:'learning',enabled:true,revision:0}]};}

test('dos módulos comprensibles sin activar ni escoger la primera interfaz por defecto',()=>{const c=setup();c.automationAccept(state());const html=c.automationModuleHtml('training');assert.match(html,/Ventanas de mejora\/decisión/);assert.match(html,/Activar seleccionados \(0\)/);assert.match(html,/Selecciona interfaz/);assert.match(html,/Desktop APP · Claude/);assert.match(html,/CLI · Claude · No disponible/);assert.equal(c.AUTOMATION_SELECTIONS.training.size,0);assert.match(c.automationModuleHtml('learning'),/Cápsulas de conocimiento/);});

test('identidad familia une alias del equipo pero mantiene otra máquina y no ofrece interfaz desconocida',()=>{const c=setup(),families=c.automationUiFamilies([app,{...cli,agent:'SubMorfeoMini',machine:'admira-macmini'},{...app,agent:'MorfeoMBP14',machine:'MacBookProNegro14'},{...app,host:'unknown',metadata_only:true}]);assert.equal(families.length,2);assert.equal(families.reduce((n,[,rows])=>n+rows.length,0),3);});

test('parada sin ACK nunca se presenta como proceso detenido ni enlaza URL insegura',()=>{const c=setup();c.automationAccept(state([{...app,mode:'learning',automation_enabled:false,execution_stop:'unconfirmed',last_run:{deliverable_url:'javascript:alert(1)'}}]));const html=c.automationModuleHtml('learning');assert.match(html,/ejecución aún sin confirmar/);assert.doesNotMatch(html,/javascript:|proceso detenido/);});

test('acción individual envía únicamente la interfaz seleccionada; parcial mantiene motivo visible',async()=>{const c=setup();c.automationAccept(state());const family=c.automationUiFamily(app);c.AUTOMATION_SELECTIONS.training.set(family,app.identity_key);let sent;c.automationRequest=async options=>{sent=JSON.parse(options.body);return {ok:false,partial:false,results:[{identity_key:app.identity_key,ok:false,reason:'human_mission_assigned'}],state:state()};};const button={dataset:{mode:'training',automationAction:'activate',family:encodeURIComponent(family)}};await c.automationHandle({type:'click',target:{closest(selector){return selector==='[data-automation-action]'?button:null;}}});assert.equal(sent.targets.length,1);assert.equal(sent.targets[0].host,'app');assert.equal(sent.targets[0].runtime,'Claude');assert.equal(sent.scope,'individual');assert.match(c.AUTOMATION_RESULTS.get('training|'+family),/misión humana/);});

test('module code compiles; stop/activation are event-only and module lives in Módulos',()=>{for(const match of source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);assert.ok(source.indexOf('id="automationModules"')>source.indexOf('id="modulesSection"'));assert.match(source,/surfaceInventory\(PULSE_CONTROL_MODEL/);const rendering=fn('pulseGroupsMarkup');assert.doesNotMatch(rendering,/pulseGroupMarkup\(unknown/);assert.match(source,/data-automation-action="stop"/);});
