/* Real data only. No demo incidents, synthetic counters or successful optimistic writes. */
(() => {
const API='https://data.yokup.com/api/installer';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const es={}, en={hvac:'Air conditioning',portal:'INSTALLER NETWORK',signin:'Sign in',logout:'Sign out',eyebrow:'LOCAL PEOPLE. CONNECTED DEVICES.',headline:'Your skills.<br>Your area.<br><em>All connected.</em>',intro:'When an Admira device needs help, you can be the solution. Receive jobs in your specialty less than 40 km away.',radius:'Proximity radius',global:'Global',where:'Work from your city',equipment:'Screens and much more',coverage:'YOUR WORKING AREA',mapPlaceholder:'Set your location to see your working area.',mapHint:'Your location helps us find nearby jobs.',start:'FROM YOUR PROFILE TO YOUR FIRST JOB',ready:'Connect with<br>what you do best.',step1:'Put yourself on the map',step1body:'Choose your working base and the equipment you specialise in.',step2:'Receive nearby incidents',step2body:'Alerts arrive in your inbox based on distance and availability.',step3:'Accept, repair and report',step3body:'See the address after accepting and record how you fixed the issue.',notificationsNote:'Alerts are saved in your portal. You can enable browser notifications while you keep it open.',register:'Create account',yourProfile:'Your installer profile',profileHint:'Your location and skills determine which jobs you receive.',name:'Name or company',email:'Email address',password:'Password · at least 12 characters',country:'Country',city:'City',workbase:'Your working base',locate:'Use my location ↗',locationHint:'Click the map or enter the coordinates of your working base.',latitude:'Latitude',longitude:'Longitude',skills:'Your specialties',screen:'Screens',network:'Networks',sensor:'IoT sensors',kiosk:'Kiosks',available:'Available to receive jobs',dataNote:'Your email and location are not public. Your location is used to calculate distance to devices.',join:'Create my account →',workspace:'YOUR WORKSPACE',edit:'Edit profile',enableAlerts:'Enable alerts',newAlerts:'New alerts',myJobs:'My open jobs',finished:'Resolved jobs',inbox:'Your incident inbox',refresh:'Refresh ↻',inboxHint:'Only you can see your inbox. Incidents refresh every 30 seconds while you are here.',footer:'The people behind connected devices.',about:'About Yokup ↗',resolveTitle:'Close intervention',resolutionLabel:'Describe the issue, the repair and how you tested it.',cancel:'Cancel',resolve:'Save and close'};
$$('[data-i18n]').forEach(el=>es[el.dataset.i18n]=el.innerHTML);
let lang=localStorage.getItem('yokup.installer.language')||'es', user=null, mode='register', map, marker, mapReady=false, polling=false, seen=new Set(), initialInbox=true, activeIncident=null, latestInbox=[], latestStats={unread:0,assigned:0,resolved:0};
const t=(a,b)=>lang==='en'?b:a;
function countries(selected='ES') {
 const list='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ');
 const names=new Intl.DisplayNames([lang],{type:'region'}), select=$('[name=country]');select.replaceChildren();
 list.map(code=>({code,name:names.of(code)})).sort((a,b)=>a.name.localeCompare(b.name,lang)).forEach(({code,name})=>{const option=document.createElement('option');option.value=code;option.textContent=name;select.append(option);});select.value=selected;
}
function language(value){lang=value==='en'?'en':'es';localStorage.setItem('yokup.installer.language',lang);document.documentElement.lang=lang;$('#language').value=lang;
 $$('[data-i18n]').forEach(el=>el.innerHTML=(lang==='en'?en:es)[el.dataset.i18n]||es[el.dataset.i18n]);countries($('[name=country]').value||'ES');setMode(mode);if(user){showUser();render(latestInbox);}health();}
async function api(path,body,method){
 const controller=new AbortController(), timeout=setTimeout(()=>controller.abort(),20000);
 try{const response=await fetch(API+path,{method:method||(body?'POST':'GET'),credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:controller.signal});const result=await response.json();if(!response.ok)throw Object.assign(new Error(result.error||t('No se pudo completar la operación.','The operation could not be completed.')),{status:response.status});return result;}
 catch(e){if(e.name==='AbortError')throw new Error(t('La conexión ha tardado demasiado. Comprueba el resultado antes de repetir.','The connection timed out. Check the result before retrying.'));throw e;}finally{clearTimeout(timeout);}
}
async function health(){try{const state=await api('/health');$('#integration').hidden=state.admira_configured;if(!state.admira_configured)$('#integration').textContent=t('Alta y portal disponibles. La conexión de equipos reales con Admira está pendiente; todavía no recibirás incidencias automáticas de producción.','Registration and portal are available. Live Admira devices are not connected yet; automatic production incidents are not active.');}catch{$('#integration').hidden=false;$('#integration').textContent=t('No hemos podido conectar con el servicio. Tu perfil no se guardará hasta recuperar la conexión.','We could not reach the service. Your profile cannot be saved until it reconnects.');}}
let googleAuth;
const REMEMBER_KEY='yk_remember_installer',WEEK=7*86400000;
function rememberedUser(){try{const r=JSON.parse(localStorage.getItem(REMEMBER_KEY)||'null');if(r&&r.exp>Date.now())return r.user;localStorage.removeItem(REMEMBER_KEY);}catch{}return '';}
function rememberUser(user,on){try{on?localStorage.setItem(REMEMBER_KEY,JSON.stringify({user,exp:Date.now()+WEEK})):localStorage.removeItem(REMEMBER_KEY);}catch{}}
function setMode(next){mode=next;const login=mode==='login',edit=mode==='edit';$$('.register-only').forEach(el=>{el.hidden=login;el.querySelectorAll('input,select').forEach(input=>{input.disabled=login;});});
 $('#account-form [name=email]').closest('label').hidden=edit;$('#account-form [name=password]').closest('label').hidden=edit;
 for(const name of ['email','password'])$(`[name=${name}]`).disabled=edit;
 $('[name=password]').autocomplete=login?'current-password':'new-password';$('#account-form [name=email]').type=login?'text':'email';$('#account-form [name=password]').minLength=login?1:12;$('#account-form .remember-line').style.display=login?'flex':'none';if(login){const u=rememberedUser();if(u){$('#account-form [name=email]').value=u;$('#account-form [name=remember]').checked=true;}}
 $('#register-tab').classList.toggle('active',!login);$('#login-tab').classList.toggle('active',login);$('#register-tab').setAttribute('aria-selected',String(!login));$('#login-tab').setAttribute('aria-selected',String(login));$('.tabs').hidden=edit;
 $('#submit-account').textContent=edit?t('Guardar perfil →','Save profile →'):login?t('Entrar →','Sign in →'):t('Crear mi cuenta →','Create my account →');$('#form-status').textContent='';googleAuth?.reset();
}
function profileForm(){const fd=new FormData($('#account-form'));return {name:fd.get('name'),email:fd.get('email'),password:fd.get('password'),country:fd.get('country'),city:fd.get('city'),latitude:Number(fd.get('latitude')),longitude:Number(fd.get('longitude')),skills:fd.getAll('skill'),available:fd.get('available')==='on',language:lang};}
function setLocation(latitude,longitude,move=true){$('[name=latitude]').value=Number(latitude).toFixed(6);$('[name=longitude]').value=Number(longitude).toFixed(6);drawZone(latitude,longitude,move);}
function drawZone(latitude,longitude,move){
 if(!mapReady)return;const coords=[],lat=latitude*Math.PI/180,lon=longitude*Math.PI/180,delta=40/6371.0088;
 for(let i=0;i<=100;i++){const bearing=i/100*2*Math.PI,phi=Math.asin(Math.sin(lat)*Math.cos(delta)+Math.cos(lat)*Math.sin(delta)*Math.cos(bearing));const lambda=lon+Math.atan2(Math.sin(bearing)*Math.sin(delta)*Math.cos(lat),Math.cos(delta)-Math.sin(lat)*Math.sin(phi));coords.push([lambda*180/Math.PI,phi*180/Math.PI]);}
 const data={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[coords]}};
 if(map.getSource('zone'))map.getSource('zone').setData(data);else{map.addSource('zone',{type:'geojson',data});map.addLayer({id:'zone-fill',type:'fill',source:'zone',paint:{'fill-color':'#96b94c','fill-opacity':.18}});map.addLayer({id:'zone-line',type:'line',source:'zone',paint:{'line-color':'#668d39','line-width':2,'line-dasharray':[3,3]}});}
 if(marker)marker.remove();marker=new maplibregl.Marker({color:'#173d32'}).setLngLat([longitude,latitude]).addTo(map);
 if(move)map.flyTo({center:[longitude,latitude],zoom:8,duration:800});$('#map-city').textContent=$('[name=city]').value||`${Number(latitude).toFixed(3)}, ${Number(longitude).toFixed(3)}`;
}
function initMap(){if(!window.maplibregl)return;try{map=new maplibregl.Map({container:'map',style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',center:[10,24],zoom:1.2,attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('load',()=>{mapReady=true;const fallback=$('.map-fallback');if(fallback)fallback.remove();if(user)drawZone(user.latitude,user.longitude,true);});map.on('click',e=>{if(mode!=='login'&&!$('#onboarding').hidden)setLocation(e.lngLat.lat,e.lngLat.wrap().lng,false);});}catch{}}
function fillProfile(){for(const key of ['name','email','country','city','latitude','longitude'])$(`[name=${key}]`).value=user[key];$$('[name=skill]').forEach(el=>el.checked=user.skills.includes(el.value));$('[name=available]').checked=user.available;drawZone(user.latitude,user.longitude,true);}
function showUser(){document.dispatchEvent(new CustomEvent('portal-auth',{detail:{kind:'installer',authenticated:true}}));
 $('#onboarding').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;$('#login-top').hidden=true;
 $('#welcome').textContent=t('Hola, ','Hello, ')+user.name;$('#profile-summary').textContent=`${user.city} · ${new Intl.DisplayNames([lang],{type:'region'}).of(user.country)} · ${user.available?t('Disponible','Available'):t('No disponible','Unavailable')}`;
 fillProfile();refresh();
}
function signedOut(){document.dispatchEvent(new CustomEvent('portal-auth',{detail:{kind:'installer',authenticated:false}}));user=null;latestInbox=[];if(marker){marker.remove();marker=null;}if(mapReady){for(const layer of ['zone-line','zone-fill'])if(map.getLayer(layer))map.removeLayer(layer);if(map.getSource('zone'))map.removeSource('zone');map.flyTo({center:[10,24],zoom:1.2});}$('#map-city').textContent=t('Tu ubicación se usa para encontrar trabajos cercanos.','Your location helps us find nearby jobs.');$('#onboarding').hidden=false;$('#dashboard').hidden=true;$('#logout').hidden=true;$('#login-top').hidden=false;$('#account-form').reset();seen.clear();initialInbox=true;setMode('login');}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function render(list){
 $('#unread-count').textContent=latestStats.unread;$('#assigned-count').textContent=latestStats.assigned;$('#resolved-count').textContent=latestStats.resolved;
 const host=$('#incidents');host.replaceChildren();
 if(!list.length){const box=node('div',undefined,'empty');box.append(node('h3',t('Tu próxima intervención empieza aquí.','Your next job starts here.')),node('p',user.available?t('Te avisaremos cuando un equipo a menos de 40 km necesite tu especialidad.','We will alert you when a device less than 40 km away needs your skills.'):t('Tu disponibilidad está desactivada. Actívala en tu perfil para recibir avisos.','Your availability is off. Enable it in your profile to receive alerts.')));host.append(box);}
 for(const incident of list){
  const card=node('article',undefined,'incident'+(!incident.read_at?' unread':'')),main=node('div'),actions=node('div',undefined,'incident-actions');
  const label=incident.status==='resolved'?t('Resuelta','Resolved'):incident.mine?t('Asignada a ti','Assigned to you'):incident.status==='open'?t('Disponible','Available'):t('Ya asignada','Already assigned');
  main.append(node('span',label,'pill'),node('small',new Date(incident.notified_at).toLocaleString(lang)),node('h3',incident.title),node('p',incident.device_name+' · '+(incident.reason==='offline'?t('Sin latido','No heartbeat'):incident.reason==='retailer'?t('Incidencia del comercio','Retailer incident'):t('Fallo reportado','Reported fault'))));
  if(incident.appointment_start)main.append(node('p',t('Cita confirmada: ','Confirmed appointment: ')+new Date(incident.appointment_start).toLocaleString(lang,{timeZone:incident.appointment_timezone})+' — '+new Date(incident.appointment_end).toLocaleTimeString(lang,{timeZone:incident.appointment_timezone})+' · '+incident.appointment_timezone+' · '+(incident.appointment_cost_cents/100).toFixed(2)+' EUR'),node('p',incident.appointment_scope));
  if(incident.description)main.append(node('p',incident.description));
  if(incident.rating_stars)main.append(node('p',`${incident.rating_stars}/5 ★ · ${incident.rating_comment||t('Valoración del comercio','Retailer review')} · ${incident.satisfied?t('Equipo funcionando','Device working'):t('El comercio solicita revisión','Retailer requests follow-up')}`));
  if(incident.mine&&incident.address){main.append(node('p',incident.address));const link=node('a',t('Abrir indicaciones ↗','Open directions ↗'));link.href='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(incident.latitude+','+incident.longitude);link.target='_blank';link.rel='noopener noreferrer';main.append(link);}
  if(incident.resolution)main.append(node('pre',incident.resolution));
  actions.append(node('strong',Number(incident.distance_km).toLocaleString(lang,{maximumFractionDigits:1})+' km'));
  if(incident.status==='open'){const accept=node('button',t('Aceptar intervención →','Accept job →'),'primary');accept.disabled=!user.available;accept.onclick=async()=>{accept.disabled=true;try{await api('/incidents/'+encodeURIComponent(incident.id)+'/accept',{});await refresh();}catch(e){$('#dashboard-status').textContent=e.message;accept.disabled=false;}};actions.append(accept);}
  if(incident.mine&&incident.status==='assigned'){const resolve=node('button',t('Registrar solución','Record solution'),'primary');resolve.onclick=()=>{activeIncident=incident.id;$('#resolution-form').reset();$('#resolution-status').textContent='';$('#resolution-dialog').showModal();};actions.append(resolve);}
  if(!incident.read_at){const read=node('button',t('Marcar leído','Mark as read'),'text-button');read.onclick=async()=>{try{await api('/notifications/'+incident.notification_id+'/read',{});await refresh();}catch(e){$('#dashboard-status').textContent=e.message;}};actions.append(read);}
  card.append(main,actions);host.append(card);
 }
}
async function refresh(){if(!user||polling)return;polling=true;try{const {notifications,stats,reputation}=await api('/inbox');latestStats=stats;$('#reputation').textContent=reputation?.count?`${Number(reputation.average).toFixed(1)} / 5 ★ · ${reputation.count} ${t('valoraciones de comercios','retailer reviews')}`:t('Todavía sin valoraciones de comercios.','No retailer reviews yet.');$('#dashboard-status').textContent='';latestInbox=notifications;render(notifications);for(const n of notifications){if(!initialInbox&&!seen.has(n.notification_id)&&!n.read_at&&n.status==='open'&&'Notification'in window&&Notification.permission==='granted')new Notification('Yokup · '+t('Incidencia cercana','Nearby incident'),{body:n.title+' · '+n.distance_km.toFixed(1)+' km',tag:n.notification_id});seen.add(n.notification_id);}initialInbox=false;}catch(e){if(e.status===401)signedOut();else $('#dashboard-status').textContent=e.message;}finally{polling=false;}}
$('#language').onchange=e=>language(e.target.value);$('#register-tab').onclick=()=>setMode('register');$('#login-tab').onclick=()=>setMode('login');$('#login-top').onclick=()=>{setMode('login');$('#account-form').scrollIntoView({behavior:'smooth'});};
$('#locate').onclick=()=>{if(!navigator.geolocation){$('#form-status').textContent=t('Introduce las coordenadas manualmente.','Enter your coordinates manually.');return;}$('#locate').disabled=true;navigator.geolocation.getCurrentPosition(p=>{setLocation(p.coords.latitude,p.coords.longitude);$('#locate').disabled=false;$('#form-status').textContent='';},()=>{$('#locate').disabled=false;$('#form-status').textContent=t('No se pudo obtener tu ubicación. Puedes elegirla en el mapa o introducir coordenadas.','Could not get your location. Choose it on the map or enter coordinates.');},{timeout:10000,maximumAge:60000});};
for(const name of ['latitude','longitude','city'])$(`[name=${name}]`).onchange=()=>{const lat=$('[name=latitude]'),lon=$('[name=longitude]');if(lat.value&&lon.value&&lat.checkValidity()&&lon.checkValidity())drawZone(Number(lat.value),Number(lon.value),name!=='city');};
googleAuth=window.YokupGoogle.mount({kind:'installer',form:$('#account-form'),getMode:()=>mode,setMode,onLogin:profile=>{user=profile;showUser();$('#dashboard').scrollIntoView({behavior:'smooth'});}});
$('#account-form').onsubmit=async e=>{e.preventDefault();const button=$('#submit-account');button.disabled=true;$('#form-status').textContent=t('Guardando…','Saving…');try{const body=profileForm();if(mode!=='login'&&!body.skills.length)throw new Error(t('Selecciona al menos una especialidad.','Select at least one specialty.'));const result=googleAuth.isSignup()?await googleAuth.complete(body):mode==='edit'?await api('/me',body,'PATCH'):await api(mode==='login'?'/login':'/register',body);if(mode==='login')rememberUser(body.email,$('#account-form [name=remember]').checked);user=result.profile;showUser();$('#dashboard').scrollIntoView({behavior:'smooth'});}catch(e){$('#form-status').textContent=e.message;}finally{button.disabled=false;}};
$('#edit-profile').onclick=()=>{$('#onboarding').hidden=false;setMode('edit');fillProfile();$('#account-form').scrollIntoView({behavior:'smooth'});};
$('#logout').onclick=async()=>{try{await api('/logout',{});signedOut();}catch(e){$('#dashboard-status').textContent=e.message;}};$('#refresh').onclick=refresh;
$('#browser-alerts').onclick=async()=>{if(!('Notification'in window)){$('#dashboard-status').textContent=t('Este navegador no admite avisos. Tu bandeja seguirá guardándolos.','This browser does not support notifications. Your inbox will still save them.');return;}const permission=await Notification.requestPermission();$('#dashboard-status').textContent=permission==='granted'?t('Avisos activados mientras mantengas este portal abierto.','Notifications enabled while this portal stays open.'):t('Avisos no activados. Puedes consultar tu bandeja en cualquier momento.','Notifications not enabled. You can check your inbox at any time.');};
$('#cancel-resolution').onclick=()=>$('#resolution-dialog').close();$('#resolution-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('.primary');button.disabled=true;try{await api('/incidents/'+encodeURIComponent(activeIncident)+'/resolve',{resolution:new FormData(e.target).get('resolution')});$('#resolution-dialog').close();await refresh();}catch(e){$('#resolution-status').textContent=e.message;}finally{button.disabled=false;}};
language(lang);initMap();api('/me').then(result=>{user=result.profile;showUser();}).catch(e=>{if(e.status!==401)$('#form-status').textContent=e.message;});
setInterval(()=>{if(!document.hidden)refresh();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
if(rememberedUser())setMode('login');
})();
