(()=>{
const $=s=>document.querySelector(s),base='https://data.yokup.com/api/portal-admin';let page=0,selected=null,assigning=false;
const skillNames={screen:'Pantallas',player:'Players',audio:'Hilo musical',hvac:'Climatización',network:'Redes',sensor:'Sensores',kiosk:'Kioscos'};
const specialties=a=>a.skills.map(s=>skillNames[s]||s).join(', ');
const el=(tag,txt,cls)=>{const n=document.createElement(tag);if(txt!==undefined)n.textContent=txt;if(cls)n.className=cls;return n;};
async function api(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'No se pudo completar la operación.'),{status:r.status});return d;}
function out(){document.querySelectorAll('#admin-workspace .admin-list').forEach(n=>n.replaceChildren());$('#admin-workspace').hidden=true;$('#admin-login').hidden=false;$('#admin-logout').hidden=true;$('#match-dialog').close();}
function cards(id,items,render){const host=$(id);host.replaceChildren();if(!items.length)host.append(el('p','No hay resultados.','muted'));for(const row of items){const c=el('article',undefined,'admin-card');render(c,row);host.append(c);}}
const button=(text,fn)=>{const b=el('button',text,'text-button');b.onclick=fn;return b;};
// «Abrir como» (06-10-2026): el superusuario usa el portal real del retailer (cuentas de marca) o del instalador.
// El servidor decide y revalida en cada petición (/api/retailer/switch, /api/portal-admin/view-as).
async function openAs(kind,id,b){b.disabled=true;$('#access-status').textContent='Abriendo el portal…';try{if(kind==='retailer'){const r=await fetch('https://data.yokup.com/api/retailer/switch',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({retailer_id:id}),signal:AbortSignal.timeout(20000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'No se pudo abrir la cuenta.');location.assign('/retailer');}else{await api('/view-as',{kind:'installer',installer_id:id});location.assign('/instalador');}}catch(e){b.disabled=false;$('#access-status').textContent=e.message;}}
const openButton=(kind,id)=>{const b=el('button',kind==='retailer'?'Abrir como retailer':'Abrir como instalador','text-button');b.onclick=()=>openAs(kind,id,b);return b;};
const brandOnly=()=>el('p','«Abrir como retailer»: solo cuentas de marca','small muted');
async function load(){try{
 const d=await api('/dashboard?'+new URLSearchParams({q:$('#admin-query').value,page}));$('#admin-login').hidden=true;$('#admin-workspace').hidden=false;$('#admin-logout').hidden=false;$('#superuser-management').hidden=d.email!=='csilva@admira.com';if(d.email==='csilva@admira.com')await loadSuperusers();$('#admin-identity').textContent='Superusuario · '+d.email;$('#access-status').textContent='';
 $('#admin-counts').replaceChildren();for(const [key,label] of [['installers','Instaladores'],['retailers','Retailers'],['sites','Establecimientos'],['open','Incidencias abiertas']]){const box=el('div');box.append(el('span',label),el('strong',d.counts[key]));$('#admin-counts').append(box);}
 $('#admin-page').textContent='Página '+(page+1);$('#admin-prev').disabled=page===0;$('#admin-next').disabled=!d.has_more;
 cards('#admin-installers',d.installers,(c,a)=>c.append(el('h3',a.name),el('p',a.email),el('p',a.city+' · '+a.country),el('p',specialties(a)),el('p',a.available?'Disponible':'No disponible'),openButton('installer',a.id)));
 cards('#admin-retailers',d.retailers,(c,a)=>c.append(el('h3',a.name),el('p',a.email),el('p',a.sites+(a.sites===1?' establecimiento':' establecimientos')),button('Ver establecimientos',()=>{$('#admin-query').value=a.name;page=0;load();}),a.brand_key?openButton('retailer',a.id):brandOnly()));
 cards('#admin-sites',d.sites,(c,s)=>c.append(el('h3',s.name),el('p',s.retailer_name),el('p',s.address+' · '+s.city+' · '+s.country),button('Buscar instaladores cercanos',()=>openMatch({site_id:s.id},s.name)),...(s.brand_key?[openButton('retailer',s.retailer_id)]:[])));
 cards('#admin-incidents',d.incidents,(c,i)=>{c.append(el('h3',i.title),el('p',(i.site_name||i.device_name)+' · '+(i.retailer_name||'Circuito')),el('p',i.status==='open'?'Pendiente de asignar':'Asignada a '+(i.installer_name||'un técnico')));if(i.status==='open')c.append(button('Hacer match y asignar',()=>openMatch({incident_id:i.id},i.title)));});
 }catch(e){if(e.status===401||e.status===403)out();else $('#access-status').textContent=e.message;}}
async function openMatch(params,title){selected={...params,title};$('#match-title').textContent=title;$('#match-skill').value='';$('#match-filter').hidden=!!params.incident_id;$('#match-dialog').showModal();await matches();}
async function matches(){if(!selected)return;$('#match-status').textContent='Buscando técnicos…';$('#match-list').replaceChildren();try{const d=await api('/candidates?'+new URLSearchParams({...selected,skill:$('#match-skill').value}));$('#match-context').textContent=d.place.address||d.place.site_name||d.place.device_name||'';$('#match-status').textContent=d.total+(d.total===1?' técnico compatible':' técnicos compatibles')+(d.total>100?' · se muestran los 100 más cercanos':'');cards('#match-list',d.matches,(c,a)=>{c.append(el('h3',a.name),el('p',a.city+' · '+a.distance_km.toFixed(1)+' km'),el('p',specialties(a)));if(d.can_assign)c.append(button('Asignar a este técnico',async()=>{
 if(assigning)return;assigning=true;const key=crypto.randomUUID();$('#match-status').textContent='Asignando…';try{await api('/assign',{incident_id:selected.incident_id,installer_id:a.id,request_key:key});$('#match-dialog').close();await load();$('#access-status').textContent='Incidencia asignada a '+a.name+'. El aviso queda en su portal.';}catch(e){await matches();$('#match-status').textContent=e.name==='TimeoutError'?'Resultado no confirmado. Cierra esta ventana y actualiza las incidencias antes de repetir.':e.message;}finally{assigning=false;}
 }));});}catch(e){$('#match-status').textContent=e.message;if(e.status===401)out();}}
async function loadSuperusers(){const d=await api('/superusers');cards('#superusers-list',d.superusers,(c,u)=>{c.append(el('p',u.email));if(u.email!=='csilva@admira.com')c.append(button('Revocar acceso',async()=>{try{await api('/superusers',{email:u.email,action:'revoke'});await loadSuperusers();$('#superusers-status').textContent='Acceso revocado y sesiones cerradas.';}catch(e){$('#superusers-status').textContent=e.message;}}));});}
$('#superuser-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/superusers',{email:e.target.elements.email.value,action:'grant'});e.target.reset();await loadSuperusers();$('#superusers-status').textContent='Acceso autorizado. Esa cuenta entrará como superusuario con Google.';}catch(e){$('#superusers-status').textContent=e.message;}finally{b.disabled=false;}};
$('#match-close').onclick=()=>{if(!assigning)$('#match-dialog').close();};$('#match-dialog').addEventListener('cancel',e=>{if(assigning)e.preventDefault();});$('#match-filter').onsubmit=e=>{e.preventDefault();matches();};$('#admin-search').onsubmit=e=>{e.preventDefault();page=0;load();};$('#admin-prev').onclick=()=>{page--;load();};$('#admin-next').onclick=()=>{page++;load();};$('#admin-logout').onclick=async()=>{try{await api('/logout',{});out();}catch(e){$('#access-status').textContent=e.message;}};document.addEventListener('portal-admin-auth',load);load();
})();
