(()=>{
const base='https://data.yokup.com/api/portal-access';let loaded;
async function api(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar el acceso.');return d;}
function sdk(){if(window.google?.accounts?.id)return Promise.resolve();if(!loaded)loaded=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=resolve;s.onerror=()=>{loaded=null;s.remove();reject(Error('No se pudo conectar con Google. Vuelve a intentarlo.'));};document.head.append(s);});return loaded;}
window.YokupGoogle={mount({kind,form,getMode,setMode,onLogin}){
 const host=document.querySelector('#portal-google'),start=host.querySelector('button'),widget=host.querySelector('[data-google-widget]'),status=host.querySelector('[role=status]'),email=form.elements.email,password=form.elements.password;let ticket='',busy=false;
 function reset(){ticket='';email.readOnly=false;password.disabled=getMode()==='edit';password.closest('label').hidden=getMode()==='edit';host.hidden=getMode()==='edit';widget.replaceChildren();status.textContent='';}
 async function accept(d){if(d.role==='superuser'){location.assign('/superusuario');return;}if(d.needs_profile){setMode('register');ticket=d.ticket;email.value=d.email;email.readOnly=true;password.value='';password.disabled=true;password.closest('label').hidden=true;if(!form.elements.name.value)form.elements.name.value=d.name;widget.replaceChildren();status.textContent='Google ha verificado '+d.email+'. Completa tu perfil para crear la cuenta.';form.elements.name.focus();}else{reset();onLogin(d.profile);}}
 start.onclick=async()=>{if(busy)return;busy=true;start.disabled=true;status.textContent='Conectando con Google…';try{await sdk();const challenge=await api('/google/challenge',{}),intent=getMode()==='login'?'login':'register';google.accounts.id.initialize({client_id:challenge.google_client_id,nonce:challenge.nonce,auto_select:false,callback:async r=>{start.disabled=true;try{status.textContent='Verificando tu cuenta…';await accept(await api('/google/login',{credential:r.credential,kind,intent}));}catch(e){status.textContent=e.message;}finally{start.disabled=false;}}});widget.replaceChildren();google.accounts.id.renderButton(widget,{type:'standard',theme:'outline',size:'large',text:'continue_with'});status.textContent='Continúa con tu cuenta de Google.';}catch(e){status.textContent=e.message;}finally{busy=false;start.disabled=false;}};
 // Reuse an existing administrative session regardless of which portal was opened.
 fetch('https://data.yokup.com/api/portal-admin/me',{credentials:'include',signal:AbortSignal.timeout(10000)}).then(r=>{if(r.ok)location.replace('/superusuario');}).catch(()=>{});
 return {reset,isSignup:()=>!!ticket,complete:async body=>{const d=await api('/google/register',{...body,kind,ticket});ticket='';return d;}};
}};
})();
