import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,call,account,event,signed} from './test-fixture.mjs';
import {handleCalls,syncCalls} from './src/calls.js';
import {hash,ingestEvent} from './src/installer-portal.js';
const origin='https://www.yokup.com';
async function admin(env,email='csilva@admira.com'){const token=crypto.randomUUID();await env.DB.prepare('INSERT OR IGNORE INTO portal_superusers VALUES(?,NULL,?, ?,NULL)').bind(email,'test',Date.now()).run();await env.DB.prepare('INSERT INTO portal_admin_sessions VALUES(?,?,?,?)').bind(await hash(token),email,'test-sub',Date.now()+3600000).run();return '__Host-yk_portal_admin='+token;}
async function req(env,path,body,cookie,extra={}){const r=await handleCalls(new Request('https://data.yokup.com/api/calls'+path,{method:body?'POST':'GET',headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),'Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined}),env);return {status:r.status,body:await r.json()};}
async function fixture(){const f=setup();f.cookie=await admin(f.env);return f;}
async function pilot(f){const p=await req(f.env,'/pilot',{},f.cookie);assert.equal(p.status,201);const d=await req(f.env,'/cases/'+encodeURIComponent(p.body.id),null,f.cookie);return {c:d.body.case,j:d.body.jobs[0]};}
const jp=(j,op)=>'/jobs/'+encodeURIComponent(j.id)+'/'+op;
const cp=(c,op)=>'/cases/'+encodeURIComponent(c.id)+(op?'/'+op:'');
const proposalBody=(previous_id=null)=>({installer_id:'pilot-screen',start_at:new Date(Date.now()+86400000).toISOString(),end_at:new Date(Date.now()+90000000).toISOString(),timezone:'Europe/Madrid',cost_cents:6500,scope:'Revisar alimentación y restaurar señal',previous_id});

test('private workspace rejects anonymous and unprivileged users; external origins cannot mutate',async()=>{const f=await fixture();assert.equal((await req(f.env,'/cases')).status,401);assert.equal((await req(f.env,'/pilot',{},f.cookie,{Origin:'https://evil.invalid'})).status,403);assert.equal((await req(f.env,'/me',null,f.cookie)).body.capabilities.telephone_ai,false);});
test('pilot is isolated from real incidents, devices and technician notifications',async()=>{const f=await fixture();const {c}=await pilot(f);assert.equal(c.is_test,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM installer_incidents').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM installer_notifications').get().n,0);assert.equal((await req(f.env,'/pilot',{},f.cookie)).body.id,c.id);});
test('human and assistant share one exclusive lease; expiry cannot steal a live attempt',async()=>{const f=await fixture(),{j}=await pilot(f),other=await admin(f.env,'other@example.test');assert.equal((await req(f.env,jp(j,'claim'),{mode:'human'},f.cookie)).status,200);assert.equal((await req(f.env,jp(j,'claim'),{mode:'assistant'},other)).status,409);const key=crypto.randomUUID();assert.equal((await req(f.env,jp(j,'start'),{channel:'browser',request_key:key},f.cookie)).status,200);assert.equal((await req(f.env,jp(j,'start'),{channel:'browser',request_key:key},f.cookie)).body.replayed,true);f.db.prepare('UPDATE call_jobs SET lease_until=0').run();await syncCalls(f.env);assert.equal((await req(f.env,jp(j,'claim'),{mode:'human'},other)).status,409);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM call_attempts').get().n,1);});
test('manual dial requires phone; result does not confirm a proposal; retry time is enforced',async()=>{const f=await fixture(),{c,j}=await pilot(f);await req(f.env,jp(j,'claim'),{mode:'human'},f.cookie);assert.equal((await req(f.env,jp(j,'start'),{channel:'manual',request_key:crypto.randomUUID()},f.cookie)).status,400);await req(f.env,cp(c,'contacts'),{kind:'retailer',name:'Contacto autorizado',phone:'+34910000000'},f.cookie);const r=await req(f.env,jp(j,'start'),{channel:'manual',request_key:crypto.randomUUID()},f.cookie);assert.equal(r.body.tel,'tel:+34910000000');assert.equal((await req(f.env,jp(j,'finish'),{outcome:'busy',notes:'Comunica al intentar contactar',retry_at:Date.now()-10},f.cookie)).status,400);const done=await req(f.env,jp(j,'finish'),{outcome:'busy',notes:'Comunica al intentar contactar',retry_at:Date.now()+60000},f.cookie);assert.equal(done.body.status,'retry');assert.equal((await req(f.env,jp(j,'claim'),{},f.cookie)).status,409);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM call_proposals').get().n,0);});
test('free assistant hands off context to human without assigning a technician',async()=>{const f=await fixture(),{c,j}=await pilot(f);await req(f.env,jp(j,'claim'),{mode:'assistant'},f.cookie);await req(f.env,jp(j,'start'),{channel:'pilot',request_key:crypto.randomUUID()},f.cookie);const r=await req(f.env,jp(j,'finish'),{outcome:'human_handoff',notes:'Prefiere hablar con una persona; mañanas disponibles.'},f.cookie);assert.equal(r.body.status,'pending');const d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.jobs[0].mode,'human');assert.match(d.attempts[0].notes,/mañanas/);assert.equal(d.proposals.length,0);});
test('versioned proposals require both acceptances and changed date clears prior agreement',async()=>{const f=await fixture(),{c}=await pilot(f);const p=await req(f.env,cp(c,'proposals'),proposalBody(),f.cookie);assert.equal(p.status,201);let accept=await req(f.env,'/proposals/'+p.body.id+'/accept',{party:'retailer',accepted:true,evidence:'Retailer de prueba acepta franja e importe'},f.cookie);assert.equal(accept.body.proposal.status,'proposed');const p2=await req(f.env,cp(c,'proposals'),proposalBody(p.body.id),f.cookie);assert.equal(p2.status,201);assert.equal((await req(f.env,'/proposals/'+p.body.id+'/accept',{party:'installer',accepted:true,evidence:'Aceptación del técnico anterior'},f.cookie)).status,409);for(const party of ['installer','retailer'])accept=await req(f.env,'/proposals/'+p2.body.id+'/accept',{party,accepted:true,evidence:'Participante de prueba acepta esta versión'},f.cookie);assert.equal(accept.body.proposal.status,'confirmed');assert.equal((await req(f.env,cp(c,'advance'),{notes:'Técnico de prueba llega al establecimiento'},f.cookie)).body.stage,'repairing');assert.equal((await req(f.env,cp(c,'advance'),{notes:'Reparación de prueba documentada'},f.cookie)).body.stage,'awaiting_rating');assert.equal((await req(f.env,cp(c,'advance'),{notes:'Retailer de prueba confirma funcionamiento',satisfied:true},f.cookie)).body.stage,'closed');});
test('calendar conflicts cannot confirm two appointments; rejection and cancellation remain distinct',async()=>{const f=await fixture();let {c}=await pilot(f);const p=await req(f.env,cp(c,'proposals'),proposalBody(),f.cookie);for(const party of ['retailer','installer'])await req(f.env,'/proposals/'+p.body.id+'/accept',{party,accepted:true,evidence:'Confirmación de prueba para esta cita'},f.cookie);f.db.prepare('UPDATE call_cases SET created_at=0').run();const second=await pilot(f);const p2=await req(f.env,cp(second.c,'proposals'),proposalBody(),f.cookie);let r;for(const party of ['retailer','installer'])r=await req(f.env,'/proposals/'+p2.body.id+'/accept',{party,accepted:true,evidence:'Segunda confirmación de prueba'},f.cookie);assert.equal(r.body.conflict,true);assert.equal(r.body.proposal.status,'proposed');assert.equal((await req(f.env,'/proposals/'+p2.body.id+'/cancel',{evidence:'Cancelada por conflicto de agenda'},f.cookie)).status,200);});
test('room credentials are scoped, SDP roles enforced, repeated ICE deduplicated and finish revokes invitation',async()=>{const f=await fixture(),{j}=await pilot(f);await req(f.env,jp(j,'claim'),{mode:'human'},f.cookie);await req(f.env,jp(j,'start'),{channel:'browser',request_key:crypto.randomUUID()},f.cookie);const room=(await req(f.env,jp(j,'room'),{},f.cookie)).body,path='/rooms/'+room.id;assert.equal((await req(f.env,path)).status,401);const guest={Authorization:'Bearer '+room.guest_token},host={Authorization:'Bearer '+room.host_token};assert.equal((await req(f.env,path,{type:'offer',sdp:'v=0\r\ns=test SDP\r\n'},null,guest)).status,403);assert.equal((await req(f.env,path,{type:'offer',sdp:'v=0\r\ns=test SDP\r\n'},null,host)).status,200);assert.equal((await req(f.env,path,null,null,guest)).body.offer,'v=0\r\ns=test SDP\r\n');for(let i=0;i<2;i++)await req(f.env,path,{type:'ice',seq:0,candidate:{candidate:'test'}},null,host);assert.equal((await req(f.env,path,null,null,guest)).body.signals.length,1);await req(f.env,jp(j,'finish'),{outcome:'other',notes:'Prueba de conexión terminada'},f.cookie);assert.equal((await req(f.env,path,null,null,guest)).status,401);});
test('real Admira event creates one job, matches correct skills/radius and denies guided pilot',async()=>{const f=await fixture();f.db.prepare("INSERT INTO retailer_accounts VALUES('r','retailer@example.test','Retailer','hash','salt',0)").run();f.db.prepare("INSERT INTO retailer_sites VALUES('s','r','Local','shop','ES','Barcelona','Calle 1',41.3874,2.1686,0)").run();await ingestEvent(await signed(f.env,event()),f.env);f.db.prepare("INSERT INTO retailer_device_links(device_id,site_id,created_at) VALUES('screen-1','s',0)").run();await call(f.env,'/register',account({name:'Near screen'}));await call(f.env,'/register',account({name:'Far screen',latitude:40,longitude:-3}));await call(f.env,'/register',account({name:'Wrong skill',skills:['audio']}));await syncCalls(f.env);await syncCalls(f.env);const c=f.db.prepare('SELECT * FROM call_cases').get(),j=f.db.prepare('SELECT * FROM call_jobs').get();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM call_jobs').get().n,1);const d=(await req(f.env,cp(c),null,f.cookie)).body;assert.deepEqual(d.candidates.map(t=>t.name),['Near screen']);assert.equal((await req(f.env,jp(j,'claim'),{mode:'assistant'},f.cookie)).status,400);assert.equal((await req(f.env,jp(j,'claim'),{mode:'ai'},f.cookie)).status,503);assert.equal((await req(f.env,cp(c,'advance'),{notes:'No permitir simular cierre real'},f.cookie)).status,400);});
test('operator permissions are retailer-scoped and revoked permissions take effect immediately',async()=>{const f=await fixture();for(const r of ['a','b'])f.db.prepare('INSERT INTO retailer_accounts VALUES(?,?,?,?,?,0)').run(r,r+'@example.test',r,'hash','salt');const tok='a'.repeat(64);f.db.prepare('INSERT INTO retailer_sessions VALUES(?,?,?)').run(await hash(tok),'a',Date.now()+60000);const op='__Host-yk_retailer='+tok;assert.equal((await req(f.env,'/me',null,op)).status,403);await req(f.env,'/operators',{action:'grant',email:'a@example.test',retailer_id:'a'},f.cookie);assert.equal((await req(f.env,'/me',null,op)).status,200);assert.equal((await req(f.env,'/operators',null,op)).status,403);f.db.prepare("INSERT INTO call_cases(id,retailer_id,title,site_name,latitude,longitude,skill,created_by,created_at) VALUES('secret','b','Private','Other',0,0,'screen','test',0)").run();assert.equal((await req(f.env,'/cases/secret',null,op)).status,404);await req(f.env,'/operators',{action:'revoke',email:'a@example.test',retailer_id:'a'},f.cookie);assert.equal((await req(f.env,'/me',null,op)).status,403);});

test('stale cancellation cannot undo a newer agreement, and closed cases cannot restart',async()=>{const f=await fixture(),{c}=await pilot(f);const first=await req(f.env,cp(c,'proposals'),proposalBody(),f.cookie);const second=await req(f.env,cp(c,'proposals'),proposalBody(first.body.id),f.cookie);for(const party of ['retailer','installer'])await req(f.env,'/proposals/'+second.body.id+'/accept',{party,accepted:true,evidence:'Aceptación explícita del piloto'},f.cookie);assert.equal((await req(f.env,'/proposals/'+first.body.id+'/cancel',{evidence:'Cancelar una versión anterior'},f.cookie)).status,409);assert.equal((await req(f.env,cp(c),null,f.cookie)).body.case.stage,'scheduled');for(const notes of ['Llegada del técnico de prueba','Reparación de prueba completada','Confirmación satisfactoria del comercio'])await req(f.env,cp(c,'advance'),{notes,satisfied:true},f.cookie);const d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.case.stage,'closed');assert.ok(d.jobs.every(j=>j.status==='done'));assert.equal((await req(f.env,'/proposals/'+second.body.id+'/cancel',{evidence:'No cancelar una intervención cerrada'},f.cookie)).status,409);assert.equal((await req(f.env,jp(d.jobs[0],'claim'),{mode:'human'},f.cookie)).status,409);});

test('real agreement assigns technician only after explicit confirmations and rejects a calendar collision',async()=>{const f=await fixture();f.db.prepare("INSERT INTO retailer_accounts VALUES('r','retailer@example.test','Retailer','hash','salt',0)").run();f.db.prepare("INSERT INTO retailer_sites VALUES('s','r','Local','shop','ES','Barcelona','Calle 1',41.3874,2.1686,0)").run();await ingestEvent(await signed(f.env,event()),f.env);f.db.prepare("INSERT INTO retailer_device_links(device_id,site_id,created_at) VALUES('screen-1','s',0)").run();await call(f.env,'/register',account({name:'Eligible technician'}));await syncCalls(f.env);const c=f.db.prepare('SELECT * FROM call_cases').get(),tech=f.db.prepare('SELECT id FROM installer_accounts').get();const p=await req(f.env,cp(c,'proposals'),{...proposalBody(),installer_id:tech.id},f.cookie);assert.equal(p.status,201);assert.equal((await req(f.env,'/proposals/'+p.body.id+'/accept',{party:'retailer',accepted:true,evidence:'Explicit real confirmation'},f.cookie)).status,400);for(const party of ['retailer','installer']){const r=await req(f.env,'/proposals/'+p.body.id+'/accept',{party,accepted:true,verbal_confirmed:true,evidence:'Confirmed exact date, scope and price'},f.cookie);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.proposal.status,party==='retailer'?'proposed':'confirmed');}const i=f.db.prepare('SELECT status,installer_id FROM installer_incidents').get();assert.equal(i.status,'assigned');assert.equal(i.installer_id,tech.id);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM installer_notifications WHERE installer_id=?').get(tech.id).n,1);});

test('call tokens require web issuance, enforce revocation, and MCP never accepts a cookie as authorization',async()=>{const {handleCallsMcp}=await import('./src/calls-mcp.js');const f=await fixture();const issued=await req(f.env,'/tokens',{label:'Smith pilot'},f.cookie);assert.equal(issued.status,201);const auth={Authorization:'Bearer '+issued.body.token};assert.equal((await req(f.env,'/me',null,null,auth)).status,200);assert.equal((await req(f.env,'/tokens',{label:'Another'},null,auth)).status,403);assert.equal((await req(f.env,'/operators',null,null,auth)).status,403);const mcp=async headers=>{const r=await handleCallsMcp(new Request('https://data.yokup.com/mcp/calls',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'calls_list',arguments:{}}})}),f.env);return r.json();};assert.equal((await mcp({Cookie:f.cookie})).error.code,-32001);assert.equal((await mcp(auth)).result.isError,false);await req(f.env,'/tokens',{revoke:issued.body.id},f.cookie);assert.equal((await req(f.env,'/me',null,null,auth)).status,401);assert.equal((await mcp(auth)).error.code,-32001);});

test('an unsatisfied pilot returns to repair instead of closing',async()=>{const f=await fixture(),{c}=await pilot(f);const p=await req(f.env,cp(c,'proposals'),proposalBody(),f.cookie);for(const party of ['retailer','installer'])await req(f.env,'/proposals/'+p.body.id+'/accept',{party,accepted:true,evidence:'Aceptación de esta cita de prueba'},f.cookie);await req(f.env,cp(c,'advance'),{notes:'Llegada de prueba'},f.cookie);await req(f.env,cp(c,'advance'),{notes:'Reparación de prueba'},f.cookie);assert.equal((await req(f.env,cp(c,'advance'),{notes:'La pantalla sigue fallando',satisfied:false},f.cookie)).body.stage,'reopened');assert.equal((await req(f.env,cp(c,'advance'),{notes:'Segunda intervención de prueba'},f.cookie)).body.stage,'repairing');});

async function conversation(f,j,outcome='no_answer'){
 assert.equal((await req(f.env,jp(j,'claim'),{mode:'assistant'},f.cookie)).status,200);
 assert.equal((await req(f.env,jp(j,'start'),{channel:'pilot',request_key:crypto.randomUUID()},f.cookie)).status,200);
 return req(f.env,jp(j,'finish'),{outcome,notes:'Resultado controlado de la prueba',...(outcome==='availability'?{availability:'Mañanas de 9 a 12'}:{})},f.cookie);
}
async function chain(f,c,body){const d=(await req(f.env,cp(c),null,f.cookie)).body;return req(f.env,cp(c,'chain'),{revision:d.chain.revision,reason:'Prueba documentada de coordinación',...body},f.cookie);}

test('automatic retries persist, respect due time and escalate after the configured limit',async()=>{
 const f=await fixture(),{c,j}=await pilot(f);
 assert.equal((await chain(f,c,{action:'policy',max_attempts:2,retry_minutes:15,coordinator:'Soporte Barcelona'})).status,200);
 const before=Date.now(),first=await conversation(f,j);
 assert.equal(first.body.status,'retry');assert.ok(first.body.retry_at>=before+15*60000);
 await syncCalls(f.env);await syncCalls(f.env);
 assert.equal((await req(f.env,jp(j,'claim'),{},f.cookie)).status,409);
 f.db.prepare('UPDATE call_jobs SET retry_at=? WHERE id=?').run(Date.now()-1,j.id);await syncCalls(f.env);
 const second=await conversation(f,j,'voicemail');assert.equal(second.body.status,'escalated');assert.equal(second.body.retry_at,null);
 let d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.chain.phase,'escalated');assert.equal(d.chain.coordinator,'Soporte Barcelona');assert.equal(d.jobs[0].attempt_count,2);
 await syncCalls(f.env);assert.equal((await req(f.env,jp(j,'claim'),{},f.cookie)).status,409);
 assert.equal((await chain(f,c,{action:'restart',job_id:j.id})).status,200);
 d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.jobs[0].attempt_count,0);assert.equal(d.attempts.length,2);assert.equal(d.jobs[0].status,'pending');
 assert.equal((await conversation(f,j,'availability')).body.status,'done');
 d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.chain.phase,'proposal');assert.equal(new Set(d.attempts.map(a=>a.cycle)).size,2);
});

test('paused chains cannot be reserved or started; resume preserves retry times and stale writes fail',async()=>{
 const f=await fixture(),{c,j}=await pilot(f);
 await req(f.env,jp(j,'claim'),{mode:'assistant'},f.cookie);
 const old=(await req(f.env,cp(c),null,f.cookie)).body.chain;
 assert.equal((await chain(f,c,{action:'pause'})).status,200);
 assert.equal((await req(f.env,jp(j,'claim'),{},f.cookie)).status,409);
 assert.equal((await req(f.env,jp(j,'start'),{channel:'pilot',request_key:crypto.randomUUID()},f.cookie)).status,409);
 assert.equal((await req(f.env,cp(c,'chain'),{action:'resume',revision:old.revision,reason:'Intento desde pantalla antigua'},f.cookie)).status,409);
 assert.equal((await chain(f,c,{action:'resume'})).status,200);
 await conversation(f,j,'busy');const due=f.db.prepare('SELECT retry_at FROM call_jobs WHERE id=?').get(j.id).retry_at;
 await chain(f,c,{action:'pause'});await chain(f,c,{action:'resume'});
 assert.equal(f.db.prepare('SELECT retry_at FROM call_jobs WHERE id=?').get(j.id).retry_at,due);
});

test('one conversation per incident and no proposal or pause during an active conversation',async()=>{
 const f=await fixture(),{c,j}=await pilot(f),p=await req(f.env,cp(c,'proposals'),proposalBody(),f.cookie);
 const installer=(await req(f.env,cp(c),null,f.cookie)).body.jobs.find(j=>j.target==='installer');
 for(const job of [j,installer])assert.equal((await req(f.env,jp(job,'claim'),{mode:'assistant'},f.cookie)).status,200);
 assert.equal((await req(f.env,jp(j,'start'),{channel:'pilot',request_key:crypto.randomUUID()},f.cookie)).status,200);
 assert.equal((await req(f.env,jp(installer,'start'),{channel:'pilot',request_key:crypto.randomUUID()},f.cookie)).status,409);
 assert.equal((await req(f.env,cp(c,'proposals'),proposalBody(p.body.id),f.cookie)).status,409);
 assert.equal((await chain(f,c,{action:'pause'})).status,409);
 assert.equal(f.db.prepare('SELECT COUNT(*) n FROM call_attempts WHERE ended_at IS NULL').get().n,1);
 assert.equal((await req(f.env,jp(j,'finish'),{outcome:'agreed',notes:'Acuerdo de prueba sin confirmar cita'},f.cookie)).status,200);
 const next=await req(f.env,cp(c,'proposals'),proposalBody(p.body.id),f.cookie);assert.equal(next.status,201);
 const d=(await req(f.env,cp(c),null,f.cookie)).body;
 assert.ok(d.jobs.every(j=>j.status==='pending'&&j.attempt_count===0&&j.cycle==='proposal:'+next.body.id));assert.equal(d.attempts.length,1);
 assert.equal(d.chain.phase,'acceptance');assert.equal(d.chain.target,'retailer');
});

test('validation follow-up opens once per repair, rejection reopens technician contact, closure stops escalations',async()=>{
 const f=await fixture(),{c}=await pilot(f),p=await req(f.env,cp(c,'proposals'),proposalBody(),f.cookie);
 for(const party of ['retailer','installer'])await req(f.env,'/proposals/'+p.body.id+'/accept',{party,accepted:true,evidence:'Aceptación expresa de la propuesta de prueba'},f.cookie);
 await req(f.env,cp(c,'advance'),{notes:'Llegada de prueba'},f.cookie);await req(f.env,cp(c,'advance'),{notes:'Reparación de prueba'},f.cookie);
 let d=(await req(f.env,cp(c),null,f.cookie)).body,retailer=d.jobs.find(j=>j.target==='retailer');assert.equal(d.chain.phase,'validation');assert.equal(retailer.status,'pending');
 await conversation(f,retailer,'agreed');await syncCalls(f.env);await syncCalls(f.env);
 d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.jobs.find(j=>j.target==='retailer').status,'done');
 await req(f.env,cp(c,'advance'),{notes:'La pantalla continúa fallando',satisfied:false},f.cookie);
 d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.chain.phase,'review');assert.equal(d.jobs.find(j=>j.target==='installer').status,'pending');
 await req(f.env,cp(c,'advance'),{notes:'Segunda reparación iniciada'},f.cookie);await req(f.env,cp(c),null,f.cookie);
 await req(f.env,cp(c,'advance'),{notes:'Segunda reparación completada'},f.cookie);
 d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.jobs.find(j=>j.target==='retailer').status,'pending');assert.notEqual(d.jobs.find(j=>j.target==='retailer').cycle,retailer.cycle);
 await conversation(f,retailer,'declined');
 await req(f.env,cp(c,'advance'),{notes:'Comercio confirma finalmente recuperación',satisfied:true},f.cookie);
 d=(await req(f.env,cp(c),null,f.cookie)).body;assert.equal(d.chain.phase,'closed');assert.ok(d.jobs.every(j=>j.status==='done'));
 assert.equal((await chain(f,c,{action:'restart',job_id:retailer.id})).status,409);
});

test('chain policy validates bounds and scoped operators cannot change another retailer chain',async()=>{
 const f=await fixture(),{c}=await pilot(f);
 assert.equal((await chain(f,c,{action:'policy',max_attempts:0,retry_minutes:15,coordinator:'Soporte'})).status,400);
 assert.equal((await chain(f,c,{action:'policy',max_attempts:2,retry_minutes:1441,coordinator:'Soporte'})).status,400);
 f.db.prepare("INSERT INTO retailer_accounts VALUES('r','operator@example.test','Retailer','hash','salt',0)").run();
 const token='a'.repeat(64);f.db.prepare('INSERT INTO retailer_sessions VALUES(?,?,?)').run(await hash(token),'r',Date.now()+60000);
 await req(f.env,'/operators',{action:'grant',email:'operator@example.test',retailer_id:'r'},f.cookie);
 assert.equal((await req(f.env,cp(c,'chain'),{action:'pause',revision:0,reason:'Acceso fuera de ámbito'},'__Host-yk_retailer='+token)).status,404);
});
